### ISSUE TITLE
Xamarin iOS ( ver. BugFender 2.0.3) - build crashes when building in Microsoft App Center

### ISSUE THREAD

**Issue by avksp** [bugfender/bugfender-xamarin#7] opened 2021-05-14 11:22 UTC
After updating nuget package to version 2.0.3 for iOS.  
While building a project for iOS in the Microsoft App Center, the build crashes with the error:

`1. MTOUCH : error MT2101: Can't resolve the reference 'System.Void ObjCRuntime.ThrowHelper::ThrowArgumentNullException(System.String)', referenced from the method 'System.Void BugfenderSDK.Bugfender::ActivateLogger(System.String)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.`

With version 2.0.2 for iOS, the project builds without errors.

**Comment by jgimenez** [comment] 2021-05-14 11:37
Seems a duplicate of #6 , you just need to update Visual Studio to the latest version

**Closed by jgimenez** 2021-05-14 11:37 UTC
